import type { CardioModality, Equipment, TrackingType, WeightMode } from '@/types';

/**
 * Curated system exercise catalog (Phase 2).
 *
 * A flat, versioned list of classic exercises with a stable `catalogKey`. The
 * seeder (`services/exerciseSeed.ts`) inserts these idempotently: a key that is
 * already present is left untouched, so a user's edits to a system exercise and
 * app updates never clash. Muscle-group labels match `constants/muscleGroups.ts`
 * so the chips and filters resolve. No images, no medical claims — just the data
 * the tracker needs.
 */
export interface SystemExerciseDef {
  catalogKey: string;
  name: string;
  primaryMuscleGroup: string;
  secondaryMuscleGroups: string[];
  equipment: string;
  trackingType: TrackingType;
  weightMode: WeightMode;
  weightMultiplier: number;
  defaultRestSeconds: number;
  searchTerms: string[];
  /** Structured default equipment (strength devices or cardio devices). */
  defaultEquipment?: Equipment;
  /** The cardio activity, for `trackingType: 'cardio'` entries. */
  cardioModality?: CardioModality;
}

/** Compact builder; weightMultiplier defaults to 1 (2 for per-hand dumbbell work). */
function b<const CatalogKey extends string>(
  catalogKey: CatalogKey,
  name: string,
  primaryMuscleGroup: string,
  secondaryMuscleGroups: string[],
  equipment: string,
  trackingType: TrackingType,
  weightMode: WeightMode,
  defaultRestSeconds: number,
  searchTerms: string[],
  weightMultiplier = 1,
): SystemExerciseDef & { catalogKey: CatalogKey } {
  return {
    catalogKey,
    name,
    primaryMuscleGroup,
    secondaryMuscleGroups,
    equipment,
    trackingType,
    weightMode,
    weightMultiplier,
    defaultRestSeconds,
    searchTerms,
  };
}

/** Compact builder for a cardio catalog entry (modality + structured device). */
function c<const CatalogKey extends string>(
  catalogKey: CatalogKey,
  name: string,
  cardioModality: CardioModality,
  defaultEquipment: Equipment,
  searchTerms: string[],
): SystemExerciseDef & { catalogKey: CatalogKey } {
  return {
    catalogKey,
    name,
    // Cardio is not muscle-specific; the whole-body group is neutral and does
    // not feed any strength muscle-group analysis (which excludes cardio anyway).
    primaryMuscleGroup: 'Ganzkörper',
    secondaryMuscleGroups: [],
    equipment: '',
    trackingType: 'cardio',
    weightMode: 'none',
    weightMultiplier: 1,
    // Cardio has no strength rest; a modest default for interval pauses.
    defaultRestSeconds: 60,
    searchTerms,
    defaultEquipment,
    cardioModality,
  };
}

export const SYSTEM_EXERCISES = [
  // ---- Brust ----------------------------------------------------------
  b(
    'bench-press',
    'Bankdrücken',
    'Brust',
    ['Trizeps', 'Vordere Schulter'],
    'Langhantel',
    'weight_reps',
    'total',
    180,
    ['bench press', 'flachbank', 'langhantel drücken'],
  ),
  b(
    'incline-bench-press',
    'Schrägbankdrücken',
    'Obere Brust',
    ['Trizeps', 'Vordere Schulter'],
    'Langhantel',
    'weight_reps',
    'total',
    180,
    ['incline bench press', 'schräg drücken'],
  ),
  b(
    'decline-bench-press',
    'Negativbankdrücken',
    'Untere Brust',
    ['Trizeps'],
    'Langhantel',
    'weight_reps',
    'total',
    180,
    ['decline bench press', 'negativ'],
  ),
  b(
    'dumbbell-bench-press',
    'Kurzhantel-Bankdrücken',
    'Brust',
    ['Trizeps', 'Vordere Schulter'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    150,
    ['dumbbell bench press', 'kh drücken'],
    2,
  ),
  b(
    'incline-dumbbell-press',
    'Schrägbank-Kurzhanteldrücken',
    'Obere Brust',
    ['Trizeps', 'Vordere Schulter'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    150,
    ['incline dumbbell press'],
    2,
  ),
  b(
    'dumbbell-fly',
    'Kurzhantel-Fliegende',
    'Brust',
    ['Vordere Schulter'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    120,
    ['dumbbell fly', 'fliegende', 'flys'],
    2,
  ),
  b(
    'cable-crossover',
    'Kabelzug-Fliegende',
    'Brust',
    ['Vordere Schulter'],
    'Kabelzug',
    'weight_reps',
    'total',
    120,
    ['cable crossover', 'kabel fliegende'],
  ),
  b(
    'pec-deck',
    'Butterfly (Maschine)',
    'Brust',
    ['Vordere Schulter'],
    'Maschine',
    'weight_reps',
    'total',
    120,
    ['pec deck', 'butterfly'],
  ),
  b(
    'machine-chest-press',
    'Brustpresse (Maschine)',
    'Brust',
    ['Trizeps', 'Vordere Schulter'],
    'Maschine',
    'weight_reps',
    'total',
    120,
    ['chest press machine', 'brustpresse'],
  ),
  b(
    'push-up',
    'Liegestütze',
    'Brust',
    ['Trizeps', 'Vordere Schulter', 'Tiefe Bauchmuskulatur/Core'],
    'Körpergewicht',
    'bodyweight_reps',
    'added_weight',
    90,
    ['push up', 'push-ups', 'liegestütz'],
  ),
  b(
    'dips-chest',
    'Dips (Brust)',
    'Untere Brust',
    ['Trizeps', 'Vordere Schulter'],
    'Dip-Barren',
    'bodyweight_reps',
    'added_weight',
    150,
    ['dips', 'barrendips'],
  ),

  // ---- Rücken ---------------------------------------------------------
  b(
    'pull-up',
    'Klimmzüge',
    'Latissimus',
    ['Bizeps', 'Rhomboiden', 'Hintere Schulter'],
    'Klimmzugstange',
    'bodyweight_reps',
    'added_weight',
    180,
    ['pull up', 'pull-ups', 'klimmzug'],
  ),
  b(
    'chin-up',
    'Klimmzüge (Untergriff)',
    'Latissimus',
    ['Bizeps', 'Brachialis'],
    'Klimmzugstange',
    'bodyweight_reps',
    'added_weight',
    180,
    ['chin up', 'untergriff'],
  ),
  b(
    'assisted-pull-up',
    'Klimmzüge (assistiert)',
    'Latissimus',
    ['Bizeps'],
    'Maschine',
    'assisted_bodyweight_reps',
    'assistance',
    150,
    ['assisted pull up', 'klimmzug hilfe'],
  ),
  b(
    'lat-pulldown',
    'Latzug',
    'Latissimus',
    ['Bizeps', 'Rhomboiden'],
    'Kabelzug',
    'weight_reps',
    'total',
    120,
    ['lat pulldown', 'latzug', 'latziehen'],
  ),
  b(
    'barbell-row',
    'Langhantelrudern',
    'Latissimus',
    ['Rhomboiden', 'Trapezmuskel mittig', 'Hintere Schulter', 'Bizeps'],
    'Langhantel',
    'weight_reps',
    'total',
    150,
    ['barbell row', 'rudern vorgebeugt'],
  ),
  b(
    'dumbbell-row',
    'Kurzhantelrudern',
    'Latissimus',
    ['Rhomboiden', 'Bizeps'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    120,
    ['dumbbell row', 'einarmiges rudern'],
    2,
  ),
  b(
    'cable-row',
    'Kabelrudern (sitzend)',
    'Latissimus',
    ['Rhomboiden', 'Trapezmuskel mittig', 'Bizeps'],
    'Kabelzug',
    'weight_reps',
    'total',
    120,
    ['seated cable row', 'kabelrudern'],
  ),
  b(
    't-bar-row',
    'T-Bar-Rudern',
    'Latissimus',
    ['Rhomboiden', 'Trapezmuskel mittig', 'Bizeps'],
    'Langhantel',
    'weight_reps',
    'total',
    150,
    ['t-bar row', 't bar'],
  ),
  b(
    'machine-row',
    'Rudern (Maschine)',
    'Latissimus',
    ['Rhomboiden', 'Bizeps'],
    'Maschine',
    'weight_reps',
    'total',
    120,
    ['machine row', 'rudermaschine'],
  ),
  b(
    'face-pull',
    'Face Pulls',
    'Hintere Schulter',
    ['Trapezmuskel mittig', 'Rhomboiden', 'Rotatorenmanschette'],
    'Kabelzug',
    'weight_reps',
    'total',
    90,
    ['face pull', 'gesichtszug'],
  ),
  b(
    'straight-arm-pulldown',
    'Überzüge am Kabel',
    'Latissimus',
    ['Trizeps'],
    'Kabelzug',
    'weight_reps',
    'total',
    90,
    ['straight arm pulldown', 'überzug'],
  ),
  b(
    'shrug',
    'Schulterheben (Shrugs)',
    'Trapezmuskel oben',
    ['Griffkraft'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    90,
    ['shrug', 'nackenziehen'],
    2,
  ),
  b(
    'back-extension',
    'Rückenstrecken (Hyperextension)',
    'Rückenstrecker',
    ['Großer Gesäßmuskel', 'Beinbeuger/Hamstrings'],
    'Körpergewicht',
    'bodyweight_reps',
    'added_weight',
    90,
    ['back extension', 'hyperextension'],
  ),

  // ---- Schultern ------------------------------------------------------
  b(
    'overhead-press',
    'Schulterdrücken (Langhantel)',
    'Vordere Schulter',
    ['Seitliche Schulter', 'Trizeps'],
    'Langhantel',
    'weight_reps',
    'total',
    150,
    ['overhead press', 'ohp', 'military press', 'schulterdrücken'],
  ),
  b(
    'dumbbell-shoulder-press',
    'Schulterdrücken (Kurzhantel)',
    'Vordere Schulter',
    ['Seitliche Schulter', 'Trizeps'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    120,
    ['dumbbell shoulder press'],
    2,
  ),
  b(
    'arnold-press',
    'Arnold-Press',
    'Vordere Schulter',
    ['Seitliche Schulter', 'Trizeps'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    120,
    ['arnold press'],
    2,
  ),
  b(
    'lateral-raise',
    'Seitheben',
    'Seitliche Schulter',
    [],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    75,
    ['lateral raise', 'seitheben'],
    2,
  ),
  b(
    'front-raise',
    'Frontheben',
    'Vordere Schulter',
    [],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    75,
    ['front raise', 'frontheben'],
    2,
  ),
  b(
    'rear-delt-fly',
    'Reverse Flys',
    'Hintere Schulter',
    ['Rhomboiden', 'Trapezmuskel mittig'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    75,
    ['rear delt fly', 'reverse fly', 'reverse flys'],
    2,
  ),
  b(
    'cable-lateral-raise',
    'Seitheben am Kabel',
    'Seitliche Schulter',
    [],
    'Kabelzug',
    'weight_reps',
    'total',
    75,
    ['cable lateral raise'],
  ),
  b(
    'upright-row',
    'Aufrechtes Rudern',
    'Seitliche Schulter',
    ['Trapezmuskel oben', 'Bizeps'],
    'Langhantel',
    'weight_reps',
    'total',
    90,
    ['upright row', 'aufrechtes rudern'],
  ),

  // ---- Bizeps / Trizeps / Unterarme -----------------------------------
  b(
    'barbell-curl',
    'Langhantel-Bizepscurls',
    'Bizeps',
    ['Brachialis', 'Unterarme'],
    'Langhantel',
    'weight_reps',
    'total',
    90,
    ['barbell curl', 'bizeps curl'],
  ),
  b(
    'dumbbell-curl',
    'Kurzhantel-Bizepscurls',
    'Bizeps',
    ['Brachialis'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    75,
    ['dumbbell curl', 'bizeps'],
    2,
  ),
  b(
    'hammer-curl',
    'Hammer Curls',
    'Brachialis',
    ['Bizeps', 'Brachioradialis'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    75,
    ['hammer curl'],
    2,
  ),
  b(
    'preacher-curl',
    'Scott-Curls',
    'Bizeps',
    ['Brachialis'],
    'SZ-Stange',
    'weight_reps',
    'total',
    90,
    ['preacher curl', 'scott curl'],
  ),
  b(
    'cable-curl',
    'Bizepscurls am Kabel',
    'Bizeps',
    ['Brachialis'],
    'Kabelzug',
    'weight_reps',
    'total',
    75,
    ['cable curl'],
  ),
  b(
    'concentration-curl',
    'Konzentrationscurls',
    'Bizeps',
    [],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    75,
    ['concentration curl'],
    1,
  ),
  b(
    'triceps-pushdown',
    'Trizepsdrücken am Kabel',
    'Trizeps',
    [],
    'Kabelzug',
    'weight_reps',
    'total',
    90,
    ['triceps pushdown', 'trizepsdrücken'],
  ),
  b(
    'overhead-triceps-extension',
    'Trizeps-Überkopfdrücken',
    'Trizeps',
    [],
    'Kurzhantel',
    'weight_reps',
    'total',
    90,
    ['overhead triceps extension', 'überkopf'],
  ),
  b(
    'skull-crusher',
    'Skull Crushers',
    'Trizeps',
    [],
    'SZ-Stange',
    'weight_reps',
    'total',
    90,
    ['skull crusher', 'stirndrücken'],
  ),
  b(
    'triceps-dips',
    'Dips (Trizeps)',
    'Trizeps',
    ['Untere Brust', 'Vordere Schulter'],
    'Dip-Barren',
    'bodyweight_reps',
    'added_weight',
    120,
    ['triceps dips', 'trizeps dips'],
  ),
  b(
    'bench-dips',
    'Bankdips',
    'Trizeps',
    ['Vordere Schulter'],
    'Bank',
    'bodyweight_reps',
    'added_weight',
    90,
    ['bench dips', 'bankdips'],
  ),
  b(
    'close-grip-bench',
    'Enges Bankdrücken',
    'Trizeps',
    ['Brust', 'Vordere Schulter'],
    'Langhantel',
    'weight_reps',
    'total',
    150,
    ['close grip bench press', 'eng'],
  ),
  b(
    'wrist-curl',
    'Handgelenkscurls',
    'Unterarme',
    ['Griffkraft'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    60,
    ['wrist curl', 'unterarm'],
    2,
  ),
  b(
    'reverse-curl',
    'Reverse Curls',
    'Brachioradialis',
    ['Unterarme', 'Bizeps'],
    'SZ-Stange',
    'weight_reps',
    'total',
    75,
    ['reverse curl', 'umgekehrte curls'],
  ),
  b(
    'farmers-walk',
    "Farmer's Walk",
    'Griffkraft',
    ['Trapezmuskel oben', 'Tiefe Bauchmuskulatur/Core', 'Unterarme'],
    'Kurzhantel',
    'duration',
    'per_hand',
    120,
    ["farmer's walk", 'farmers walk', 'koffertragen'],
    2,
  ),

  // ---- Rumpf / Core ---------------------------------------------------
  b(
    'plank',
    'Plank (Unterarmstütz)',
    'Tiefe Bauchmuskulatur/Core',
    ['Gerader Bauchmuskel'],
    'Körpergewicht',
    'duration',
    'none',
    60,
    ['plank', 'planke', 'unterarmstütz'],
  ),
  b(
    'side-plank',
    'Side Plank',
    'Schräge Bauchmuskeln',
    ['Tiefe Bauchmuskulatur/Core'],
    'Körpergewicht',
    'duration',
    'none',
    45,
    ['side plank', 'seitstütz'],
  ),
  b(
    'crunch',
    'Crunches',
    'Gerader Bauchmuskel',
    [],
    'Körpergewicht',
    'bodyweight_reps',
    'added_weight',
    45,
    ['crunch', 'crunches', 'bauchpresse'],
  ),
  b(
    'hanging-leg-raise',
    'Hanging Leg Raises',
    'Gerader Bauchmuskel',
    ['Hüftbeuger'],
    'Klimmzugstange',
    'bodyweight_reps',
    'added_weight',
    75,
    ['hanging leg raise', 'beinheben hängend'],
  ),
  b(
    'lying-leg-raise',
    'Beinheben (liegend)',
    'Gerader Bauchmuskel',
    ['Hüftbeuger'],
    'Körpergewicht',
    'bodyweight_reps',
    'added_weight',
    60,
    ['lying leg raise', 'beinheben'],
  ),
  b(
    'dead-bug',
    'Dead Bug',
    'Tiefe Bauchmuskulatur/Core',
    ['Gerader Bauchmuskel'],
    'Körpergewicht',
    'reps_only',
    'none',
    45,
    ['dead bug', 'toter käfer'],
  ),
  b(
    'russian-twist',
    'Russian Twist',
    'Schräge Bauchmuskeln',
    ['Gerader Bauchmuskel'],
    'Körpergewicht',
    'reps_only',
    'none',
    45,
    ['russian twist', 'rumpfrotation'],
  ),
  b(
    'cable-crunch',
    'Crunches am Kabel',
    'Gerader Bauchmuskel',
    [],
    'Kabelzug',
    'weight_reps',
    'total',
    60,
    ['cable crunch', 'kabel crunch'],
  ),
  b(
    'ab-wheel',
    'Bauchroller (Ab Wheel)',
    'Tiefe Bauchmuskulatur/Core',
    ['Gerader Bauchmuskel', 'Latissimus'],
    'Körpergewicht',
    'bodyweight_reps',
    'none',
    75,
    ['ab wheel', 'bauchroller', 'rollout'],
  ),
  b(
    'hollow-hold',
    'Hollow Hold',
    'Gerader Bauchmuskel',
    ['Tiefe Bauchmuskulatur/Core'],
    'Körpergewicht',
    'duration',
    'none',
    45,
    ['hollow hold'],
  ),

  // ---- Beine: Quadrizeps ----------------------------------------------
  b(
    'back-squat',
    'Kniebeugen',
    'Quadrizeps',
    ['Großer Gesäßmuskel', 'Beinbeuger/Hamstrings', 'Unterer Rücken'],
    'Langhantel',
    'weight_reps',
    'total',
    210,
    ['back squat', 'kniebeuge', 'squat'],
  ),
  b(
    'front-squat',
    'Frontkniebeugen',
    'Quadrizeps',
    ['Großer Gesäßmuskel', 'Tiefe Bauchmuskulatur/Core'],
    'Langhantel',
    'weight_reps',
    'total',
    210,
    ['front squat', 'frontkniebeuge'],
  ),
  b(
    'leg-press',
    'Beinpresse',
    'Quadrizeps',
    ['Großer Gesäßmuskel', 'Beinbeuger/Hamstrings'],
    'Maschine',
    'weight_reps',
    'total',
    150,
    ['leg press', 'beinpresse'],
  ),
  b(
    'hack-squat',
    'Hackenschmidt-Kniebeuge',
    'Quadrizeps',
    ['Großer Gesäßmuskel'],
    'Maschine',
    'weight_reps',
    'total',
    150,
    ['hack squat', 'hackenschmidt'],
  ),
  b(
    'leg-extension',
    'Beinstrecker',
    'Quadrizeps',
    [],
    'Maschine',
    'weight_reps',
    'total',
    90,
    ['leg extension', 'beinstrecker'],
  ),
  b(
    'bulgarian-split-squat',
    'Bulgarian Split Squat',
    'Quadrizeps',
    ['Großer Gesäßmuskel', 'Beinbeuger/Hamstrings'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    120,
    ['bulgarian split squat', 'ausfallschritt erhöht'],
    2,
  ),
  b(
    'lunge',
    'Ausfallschritte',
    'Quadrizeps',
    ['Großer Gesäßmuskel', 'Beinbeuger/Hamstrings'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    120,
    ['lunge', 'ausfallschritt'],
    2,
  ),
  b(
    'goblet-squat',
    'Goblet Squat',
    'Quadrizeps',
    ['Großer Gesäßmuskel'],
    'Kurzhantel',
    'weight_reps',
    'total',
    120,
    ['goblet squat'],
  ),
  b(
    'step-up',
    'Step-ups',
    'Quadrizeps',
    ['Großer Gesäßmuskel'],
    'Kurzhantel',
    'weight_reps',
    'per_hand',
    90,
    ['step up', 'aufsteiger'],
    2,
  ),

  // ---- Beine: Hüfte / Hamstrings / Gesäß ------------------------------
  b(
    'deadlift',
    'Kreuzheben',
    'Beinbeuger/Hamstrings',
    ['Großer Gesäßmuskel', 'Unterer Rücken', 'Latissimus', 'Griffkraft'],
    'Langhantel',
    'weight_reps',
    'total',
    210,
    ['deadlift', 'kreuzheben'],
  ),
  b(
    'romanian-deadlift',
    'Rumänisches Kreuzheben',
    'Beinbeuger/Hamstrings',
    ['Großer Gesäßmuskel', 'Unterer Rücken'],
    'Langhantel',
    'weight_reps',
    'total',
    180,
    ['romanian deadlift', 'rdl', 'rumänisch'],
  ),
  b(
    'hip-thrust',
    'Hip Thrust',
    'Großer Gesäßmuskel',
    ['Beinbeuger/Hamstrings'],
    'Langhantel',
    'weight_reps',
    'total',
    150,
    ['hip thrust', 'hüftstoß'],
  ),
  b(
    'glute-bridge',
    'Glute Bridge',
    'Großer Gesäßmuskel',
    ['Beinbeuger/Hamstrings'],
    'Körpergewicht',
    'bodyweight_reps',
    'added_weight',
    90,
    ['glute bridge', 'beckenheben'],
  ),
  b(
    'leg-curl',
    'Beinbeuger (Maschine)',
    'Beinbeuger/Hamstrings',
    [],
    'Maschine',
    'weight_reps',
    'total',
    90,
    ['leg curl', 'beinbeuger', 'beincurl'],
  ),
  b(
    'good-morning',
    'Good Morning',
    'Beinbeuger/Hamstrings',
    ['Großer Gesäßmuskel', 'Unterer Rücken'],
    'Langhantel',
    'weight_reps',
    'total',
    150,
    ['good morning'],
  ),
  b(
    'cable-pull-through',
    'Cable Pull-Through',
    'Großer Gesäßmuskel',
    ['Beinbeuger/Hamstrings'],
    'Kabelzug',
    'weight_reps',
    'total',
    90,
    ['pull through'],
  ),
  b(
    'hip-abduction',
    'Abduktoren (Maschine)',
    'Mittlerer Gesäßmuskel',
    ['Abduktoren'],
    'Maschine',
    'weight_reps',
    'total',
    75,
    ['hip abduction', 'abduktoren'],
  ),
  b(
    'hip-adduction',
    'Adduktoren (Maschine)',
    'Adduktoren',
    [],
    'Maschine',
    'weight_reps',
    'total',
    75,
    ['hip adduction', 'adduktoren'],
  ),

  // ---- Waden / Schienbein ---------------------------------------------
  b(
    'standing-calf-raise',
    'Wadenheben (stehend)',
    'Waden',
    [],
    'Maschine',
    'weight_reps',
    'total',
    75,
    ['standing calf raise', 'wadenheben'],
  ),
  b(
    'seated-calf-raise',
    'Wadenheben (sitzend)',
    'Waden',
    [],
    'Maschine',
    'weight_reps',
    'total',
    75,
    ['seated calf raise'],
  ),
  b(
    'tibia-raise',
    'Schienbeinheben',
    'Schienbeinmuskel',
    [],
    'Körpergewicht',
    'bodyweight_reps',
    'added_weight',
    60,
    ['tibialis raise', 'schienbein'],
  ),

  // ---- Ganzkörper / funktionell ---------------------------------------
  b(
    'kettlebell-swing',
    'Kettlebell Swing',
    'Großer Gesäßmuskel',
    ['Beinbeuger/Hamstrings', 'Unterer Rücken', 'Vordere Schulter'],
    'Kettlebell',
    'weight_reps',
    'total',
    90,
    ['kettlebell swing', 'kb swing'],
  ),
  b(
    'clean-and-press',
    'Umsetzen und Drücken',
    'Ganzkörper',
    ['Vordere Schulter', 'Quadrizeps', 'Trapezmuskel oben'],
    'Langhantel',
    'weight_reps',
    'total',
    180,
    ['clean and press', 'umsetzen'],
  ),
  b(
    'thruster',
    'Thruster',
    'Ganzkörper',
    ['Quadrizeps', 'Vordere Schulter', 'Großer Gesäßmuskel'],
    'Langhantel',
    'weight_reps',
    'total',
    150,
    ['thruster'],
  ),
  b(
    'burpee',
    'Burpees',
    'Ganzkörper',
    ['Brust', 'Quadrizeps'],
    'Körpergewicht',
    'reps_only',
    'none',
    90,
    ['burpee', 'burpees'],
  ),
  b(
    'mountain-climber',
    'Mountain Climbers',
    'Tiefe Bauchmuskulatur/Core',
    ['Hüftbeuger', 'Vordere Schulter'],
    'Körpergewicht',
    'duration',
    'none',
    45,
    ['mountain climber', 'bergsteiger'],
  ),
  b(
    'trx-row',
    'TRX Rows',
    'Latissimus',
    ['Rhomboiden', 'Bizeps', 'Hintere Schulter'],
    'TRX/Schlingentrainer',
    'bodyweight_reps',
    'none',
    90,
    ['trx row', 'schlingenrudern', 'inverted row'],
  ),
  b(
    'trx-push-up',
    'TRX Push-ups',
    'Brust',
    ['Trizeps', 'Vordere Schulter', 'Tiefe Bauchmuskulatur/Core'],
    'TRX/Schlingentrainer',
    'bodyweight_reps',
    'none',
    90,
    ['trx push up', 'schlingen liegestütz'],
  ),
  b(
    'band-pull-apart',
    'Band Pull-Apart',
    'Hintere Schulter',
    ['Rhomboiden', 'Trapezmuskel mittig'],
    'Widerstandsband',
    'reps_only',
    'none',
    60,
    ['band pull apart', 'bandziehen'],
  ),
  b(
    'inverted-row',
    'Rudern am Reck (Inverted Row)',
    'Latissimus',
    ['Rhomboiden', 'Bizeps', 'Hintere Schulter'],
    'Körpergewicht',
    'bodyweight_reps',
    'added_weight',
    90,
    ['inverted row', 'reck rudern'],
  ),

  // ---- Mobilität / Ergänzungen ----------------------------------------
  b(
    'dead-hang',
    'Dead Hang',
    'Griffkraft',
    ['Latissimus', 'Unterarme'],
    'Klimmzugstange',
    'duration',
    'none',
    90,
    ['dead hang', 'hängen'],
  ),
  b(
    'hip-flexor-stretch',
    'Hüftbeuger-Dehnung',
    'Hüftbeuger',
    [],
    'Körpergewicht',
    'duration',
    'none',
    30,
    ['hip flexor stretch', 'hüftbeuger dehnen'],
  ),
  b(
    'cat-cow',
    'Katze-Kuh (Mobilisation)',
    'Unterer Rücken',
    ['Tiefe Bauchmuskulatur/Core'],
    'Körpergewicht',
    'reps_only',
    'none',
    30,
    ['cat cow', 'katze kuh'],
  ),
  b(
    'bird-dog',
    'Bird Dog',
    'Unterer Rücken',
    ['Tiefe Bauchmuskulatur/Core', 'Großer Gesäßmuskel'],
    'Körpergewicht',
    'reps_only',
    'none',
    30,
    ['bird dog'],
  ),
  b(
    'neck-flexion',
    'Nacken-Kräftigung',
    'Nacken',
    [],
    'Körpergewicht',
    'reps_only',
    'none',
    45,
    ['neck flexion', 'nacken'],
  ),

  // ---- Cardio ---------------------------------------------------------
  c('cardio-running', 'Laufen', 'running', 'unspecified', [
    'laufen',
    'joggen',
    'run',
    'running',
    'jog',
    'outdoor',
  ]),
  c('cardio-treadmill', 'Laufband', 'running', 'treadmill', [
    'laufband',
    'treadmill',
    'laufen indoor',
  ]),
  c('cardio-walking', 'Gehen', 'walking', 'unspecified', [
    'gehen',
    'walking',
    'walk',
    'spazieren',
  ]),
  c('cardio-cycling-outdoor', 'Fahrradfahren Outdoor', 'cycling', 'unspecified', [
    'radfahren',
    'fahrrad',
    'cycling',
    'bike',
    'rad outdoor',
  ]),
  c('cardio-ergometer', 'Fahrradergometer', 'cycling', 'ergometer', [
    'ergometer',
    'heimtrainer',
    'spinning',
    'indoor bike',
  ]),
  c('cardio-rowing', 'Rudermaschine', 'rowing', 'rowing_machine', [
    'rudern',
    'rowing',
    'ergo',
    'concept2',
  ]),
  c('cardio-elliptical', 'Crosstrainer', 'elliptical', 'elliptical', [
    'crosstrainer',
    'elliptical',
    'ellipsentrainer',
  ]),
  c('cardio-stair-climber', 'Stair Climber', 'stair_climbing', 'stair_climber', [
    'stairmaster',
    'stair climber',
    'treppen',
    'stepper',
  ]),
  c('cardio-swimming', 'Schwimmen', 'swimming', 'pool', [
    'schwimmen',
    'swimming',
    'swim',
    'pool',
    'bahnen',
  ]),
  c('cardio-jump-rope', 'Seilspringen', 'jump_rope', 'jump_rope', [
    'seilspringen',
    'springseil',
    'jump rope',
    'rope skipping',
  ]),
] as const satisfies readonly SystemExerciseDef[];

/** Stable keys used to localise untouched entries without relying on their name. */
export type SystemExerciseCatalogKey = (typeof SYSTEM_EXERCISES)[number]['catalogKey'];
